apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-staging
spec:
  project: default
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/hivagr/kustomize-helm
    targetRevision: HEAD
    path: helmfile/grafana/staging
    plugin:
      name: helmfile
